version: "3.8"

networks:
  my-app-net:
    driver: bridge

services:

  backend:
    container_name: myapp_backend
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=${PORT}
    volumes:
      - ./src:/var/www/backend/src
      - ./test:/var/www/backend/test
    working_dir: /var/www/backend
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    env_file: .env
    networks:
      - my-app-net

  mysql:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    volumes:
      - myapp_mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - my-app-net

  redis:
    # Example Service
    container_name: myapp_redis
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - myapp_redis_data:/data
    networks:
      - my-app-net
volumes:
  myapp_mysql_data:
  myapp_redis_data:
